mongo_user = "my_mongo_username"
mongo_pass = "my_mongo_password"
mongo_url = "my_mongo_url"
log_file = "log.txt" #feel free to change the filename
backlog_file = "backlog.csv" #feel free to change the filename
resource_folder = "resources"
captures_folder = "captures"
twitter_consumer_key = "my_consumer_key"
twitter_consumer_secret = "my_consumer_secret"
twitter_access_token = "my_access_token"
twitter_access_secret = "my_access_secret"
